const actionTypes = {
  FETCH_COURSES_START: 'FETCH_SUBSCRIPTIONS_START',
  FETCH_COURSES_FAIL: 'FETCH_SUBSCRIPTIONS_FAIL',
  FETCH_COURSES_SUCCESS: 'FETCH_SUBSCRIPTIONS_SUCCESS',

  FETCH_SINGLE_COURSE_SUCCESS: 'FETCH_SINGLE_SUBSCRIPTION_SUCCESS',

  CHANGE_SEARCH_TEXT: 'CHANGE_SEARCH_TEXT',

  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_PUSH_NEW_COURSE: 'AUTH_PUSH_NEW_COURSE',

  SET_CURRENT_USER: 'SET_CURRENT_USER',

  CHECKOUT_PRODUCT_START: 'CHECKOUT_PRODUCT_START',
  CHECKOUT_PRODUCT: 'CHECKOUT_PRODUCT',
  CHECKOUT_DISCOUNT: 'CHECKOUT_DISCOUNT',
  CHECKOUT_REMOVE_PRODUCT: 'CHECKOUT_REMOVE_PRODUCT',

  NOTIFICATION_INIT: 'NOTIFICATION_SUCCESS',
  NOTIFICATION_CLOSE: 'NOTIFICATION_CLOSE'
};

export default actionTypes;
