const actionTypes = {
  FETCH_COURSES_START: 'FETCH_SUBSCRIPTIONS_START',
  FETCH_COURSES_FAIL: 'FETCH_SUBSCRIPTIONS_FAIL',
  FETCH_COURSES_SUCCESS: 'FETCH_SUBSCRIPTIONS_SUCCESS',

  FETCH_SINGLE_COURSE_SUCCESS: 'FETCH_SINGLE_SUBSCRIPTION_SUCCESS',

  CHANGE_TOPBAR_TITLE: 'CHANGE_TOPBAR_TITLE',

  CHANGE_VISIBILITY_SUCCESS: 'CHANGE_VISIBILITY_SUCCESS',

  CHANGE_SEARCH_TEXT: 'CHANGE_SEARCH_TEXT',

  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  SET_CURRENT_USER: 'SET_CURRENT_USER',

  NOTIFICATION: 'NOTIFICATION',
  NOTIFICATION_HIDE: 'NOTIFICATION_HIDE'
};

export default actionTypes;
